### ISSUE TITLE
Graceful shutdown alert not working (PM2)

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [keybase/keybase-bot#245]
### Code
```
['SIGINT', 'SIGTERM', 'SIGQUIT']
  .forEach(signal => process.on(signal, async () => {
    console.log("Shutting down server.");
    try {
      await bot.chat.send(botChannel, { body: 'Shutting down server.' });
    } catch (error) {
      console.log(error);
    } finally {
      await bot.deinit();
      process.exit(0);
    }
  }));
```

### Error

```
^C
Shutting down server.
Error: Login required
    at new ErrorWithCode (/workspaces/social-graph/node_modules/keybase-bot/lib/client-base/index.js:63:28)
    at Chat.<anonymous> (/workspaces/social-graph/node_modules/keybase-bot/lib/client-base/index.js:141:35)
    at step (/workspaces/social-graph/node_modules/keybase-bot/lib/client-base/index.js:46:23)
    at Object.next (/workspaces/social-graph/node_modules/keybase-bot/lib/client-base/index.js:27:53)
    at fulfilled (/workspaces/social-graph/node_modules/keybase-bot/lib/client-base/index.js:18:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 0
}
```

**Comment by roychowdhuryrohit-dev** [comment]
Solved by using `{ useDetachedService: true }` ;-)

**Comment by roychowdhuryrohit-dev** [comment]
Now I'm facing the same problem while running with pm2.

**Comment by roychowdhuryrohit-dev** [comment]
Adding the --treekill flag set to false in` pm2 start` solved this issue.
